# Generated by Django 5.2.15 on 2026-06-14 06:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                (
                    "branch_type",
                    models.CharField(
                        choices=[
                            ("dinners", "4pm Dinners"),
                            ("coffee", "Coffee Sundays"),
                            ("sunday", "Kids Church"),
                            ("kids", "Lighthouse Kids"),
                            ("youth", "Lighthouse Youth"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("green", "Green (Dinners)"),
                            ("amber", "Amber (Coffee)"),
                            ("coral", "Coral (Kids Church)"),
                            ("blue", "Blue (Kids)"),
                            ("purple", "Purple (Youth)"),
                            ("slate", "Slate (Admin/Other)"),
                        ],
                        default="green",
                        max_length=20,
                    ),
                ),
                ("icon", models.CharField(default="🍽️", max_length=10)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("kiosk_pin_hash", models.CharField(max_length=256)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_no_fee_programme",
                    models.BooleanField(
                        default=False,
                        help_text="Hides all credit balances and top-up buttons.",
                    ),
                ),
                ("is_children_programme", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Branches",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=150)),
                ("surname", models.CharField(db_index=True, max_length=100)),
                ("primary_contact", models.CharField(max_length=100)),
                ("pin_hash", models.CharField(max_length=256)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "recovery_question",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "What street did you grow up on?"',
                        max_length=255,
                    ),
                ),
                ("recovery_answer", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name_plural": "Families",
                "ordering": ["surname", "display_name"],
                "unique_together": {("surname", "primary_contact")},
            },
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "enrolled_branches",
                    models.ManyToManyField(
                        blank=True, related_name="enrolled_children", to="meals.branch"
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="meals.family",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Children",
                "ordering": ["first_name", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(default="🎟️", max_length=10)),
                ("credit_cost", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "topup_bundle",
                    models.PositiveIntegerField(
                        default=10, help_text="Units per standard top-up bundle"
                    ),
                ),
                (
                    "topup_credits",
                    models.PositiveIntegerField(
                        default=10, help_text="Credits added per bundle purchase"
                    ),
                ),
                (
                    "price_aud",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="AUD price for one top-up bundle. Leave blank to disable online purchasing.",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="meals.branch",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_active", "order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QRCodeNonce",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("credit_units", models.DecimalField(decimal_places=2, max_digits=10)),
                ("child_ids", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="qr_nonces",
                        to="meals.branch",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="qr_nonces",
                        to="meals.family",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SquarePaymentOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cart_summary",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "2× Adult Meal, 1× Kids Meal"',
                        max_length=500,
                    ),
                ),
                (
                    "cart_data",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of {name, quantity, unit_price_cents}",
                    ),
                ),
                (
                    "credits_to_add",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("amount_aud", models.DecimalField(decimal_places=2, max_digits=8)),
                ("square_order_id", models.CharField(blank=True, max_length=200)),
                (
                    "square_payment_link_id",
                    models.CharField(blank=True, max_length=200),
                ),
                ("square_payment_id", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="square_orders",
                        to="meals.branch",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="square_orders",
                        to="meals.family",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credit_delta", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("qr_redemption", "QR Redemption"),
                            ("manual_kiosk", "Manual Kiosk Entry"),
                            ("admin_adjustment", "Admin Adjustment"),
                            ("credit_top_up", "Credit Top-Up"),
                            ("online_topup", "Online Top-Up (Square)"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "performed_by",
                    models.CharField(
                        choices=[
                            ("system_qr", "System (QR)"),
                            ("kiosk_volunteer", "Kiosk Volunteer"),
                            ("admin", "Admin"),
                            ("square_online", "Square Online"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="meals.branch",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="meals.family",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_date",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_records",
                        to="meals.branch",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_records",
                        to="meals.family",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_record",
                        to="meals.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-session_date", "family__surname"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceChild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children_present",
                        to="meals.attendancerecord",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="meals.child"
                    ),
                ),
            ],
            options={
                "unique_together": {("record", "child")},
            },
        ),
        migrations.CreateModel(
            name="FamilyBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balances",
                        to="meals.branch",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balances",
                        to="meals.family",
                    ),
                ),
            ],
            options={
                "ordering": ["branch__order", "family__surname"],
                "unique_together": {("family", "branch")},
            },
        ),
    ]
