# Generated by Django 6.0.4 on 2026-04-20 07:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=150)),
                ('surname', models.CharField(db_index=True, max_length=100)),
                ('primary_contact', models.CharField(max_length=100)),
                ('pin_hash', models.CharField(max_length=256)),
                ('credit_units', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Families',
                'ordering': ['surname', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='MealPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('adult', 'Adult'), ('child', 'Child')], max_length=10)),
                ('unit_cost', models.PositiveIntegerField()),
                ('active_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Meal Pricings',
                'ordering': ['-active_from'],
            },
        ),
        migrations.CreateModel(
            name='QRCodeNonce',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_units', models.PositiveIntegerField()),
                ('adult_count', models.PositiveIntegerField(default=0)),
                ('child_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qr_nonces', to='meals.family')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_delta', models.IntegerField()),
                ('reason', models.CharField(choices=[('qr_redemption', 'QR Redemption'), ('manual_kiosk_entry', 'Manual Kiosk Entry'), ('admin_adjustment', 'Admin Adjustment'), ('credit_top_up', 'Credit Top-Up')], max_length=30)),
                ('performed_by', models.CharField(choices=[('system_qr', 'System (QR)'), ('kiosk_volunteer', 'Kiosk Volunteer'), ('admin', 'Admin')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='meals.family')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
