# Generated by Django 5.2.15 on 2026-07-05 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("square", "Square"),
                            ("stripe", "Stripe"),
                            ("stripe_ytd", "Stripe YTD Unified"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "label",
                    models.CharField(help_text="e.g. 'June 2026'", max_length=100),
                ),
                (
                    "uploaded_file",
                    models.FileField(upload_to="finances/uploads/%Y/%m/"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("row_count", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="PatternRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Label only, e.g. 'Meal credits'", max_length=100
                    ),
                ),
                (
                    "pattern",
                    models.CharField(
                        help_text="Python regex, matched against the transaction description.",
                        max_length=500,
                    ),
                ),
                ("fixed_ministry", models.CharField(blank=True, max_length=100)),
                (
                    "priority",
                    models.IntegerField(
                        default=100, help_text="Lower numbers are tried first."
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="ItemPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=200)),
                (
                    "variation_name",
                    models.CharField(blank=True, default="Regular", max_length=100),
                ),
                ("ministry", models.CharField(max_length=100)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["item_name", "variation_name"],
                "unique_together": {("item_name", "variation_name")},
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("square", "Square"),
                            ("stripe", "Stripe"),
                            ("stripe_ytd", "Stripe YTD Unified"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date", models.DateField()),
                ("ministry", models.CharField(default="Unknown", max_length=100)),
                ("item", models.CharField(blank=True, max_length=300)),
                ("qty", models.IntegerField(default=1)),
                ("gross", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fees", models.DecimalField(decimal_places=2, max_digits=10)),
                ("net", models.DecimalField(decimal_places=2, max_digits=10)),
                ("external_id", models.CharField(blank=True, max_length=200)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="finances.importbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "id"],
                "indexes": [
                    models.Index(
                        fields=["batch", "ministry"],
                        name="finances_tr_batch_i_f352c0_idx",
                    ),
                    models.Index(fields=["date"], name="finances_tr_date_839ab4_idx"),
                ],
            },
        ),
    ]
